version: '3'
services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: root
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
